name: Tự động cập nhật dữ liệu TikTok

on:
  schedule:
    - cron: '0 1 * * *' # Chạy vào 1h sáng mỗi ngày (giờ UTC, khoảng 8h sáng VN)
  workflow_dispatch: # Cho phép bạn bấm nút chạy thủ công nếu muốn

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kiểm tra mã nguồn
        uses: actions/checkout@v2

      - name: Cài đặt Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cài đặt thư viện
        run: pip install -r requirements.txt

      - name: Chạy code lấy dữ liệu
        env:
          MY_API_KEY: ${{ secrets.SERPAPI_KEY }} # Bảo mật mã API của bạn
        run: python main.py

      - name: Lưu file kết quả lên GitHub
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'action@github.com'
          git add *.xlsx
          git commit -m "Auto update data"
          git push
